### ISSUE TITLE
Improve datasets test coverage to 90%

### ISSUE THREAD

**Issue by aCampello** [wellcometrust/WellcomeML#149]
Currently test coverage of datasets is 68.61%

- [ ] Improve `datasets/conll.py` coverage to > 90%
- [ ] Improve `datasets/download.py` coverage to > 90%
- [ ] Improve `datasets/hoc.py` coverage to > 90%
- [ ] Improve `datasets/winer.py` coverage to > 90%

**Comment by aCampello** [comment]
Here is a coverage map

https://codecov.io/gh/wellcometrust/WellcomeML/tree/master/wellcomeml/datasets

**Comment by ivyleavedtoadflax** [comment]
I'll have a look at this one

**Comment by ivyleavedtoadflax** [comment]
Incidentally, I can't get the winer dataset from s3, for some reason it is forbidded. Might need to check the acl on that file.

```
2020-10-02 14:12:29 wellcomeml.logger INFO: Could not find dataset conll. Downloading from S3
2020-10-02 14:12:33 wellcomeml.logger INFO: Could not find dataset hoc. Downloading from S3
2020-10-02 14:12:39 wellcomeml.logger INFO: Could not find dataset winer. Downloading from S3
Traceback (most recent call last):
  File "foo.py", line 7, in <module>
    check_cache_and_download("winer")
  File "/home/matthew/Documents/wellcome/WellcomeML/wellcomeml/datasets/download.py", line 45, in check_cache_and_download
    tmp_file,
  File "/home/matthew/Documents/wellcome/WellcomeML/build/virtualenv/lib/python3.7/site-packages/boto3/s3/inject.py", line 172, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/home/matthew/Documents/wellcome/WellcomeML/build/virtualenv/lib/python3.7/site-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/home/matthew/Documents/wellcome/WellcomeML/build/virtualenv/lib/python3.7/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/home/matthew/Documents/wellcome/WellcomeML/build/virtualenv/lib/python3.7/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/home/matthew/Documents/wellcome/WellcomeML/build/virtualenv/lib/python3.7/site-packages/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/home/matthew/Documents/wellcome/WellcomeML/build/virtualenv/lib/python3.7/site-packages/s3transfer/download.py", line 343, in _submit
    **transfer_future.meta.call_args.extra_args
  File "/home/matthew/Documents/wellcome/WellcomeML/build/virtualenv/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/matthew/Documents/wellcome/WellcomeML/build/virtualenv/lib/python3.7/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

**Comment by aCampello** [comment]
Let me have a look

**Comment by aCampello** [comment]
Somehow it was public - thanks for finding this bug. Should work now, can you try again?

**Comment by ivyleavedtoadflax** [comment]
thanks!

**Comment by ivyleavedtoadflax** [comment]
yep that works.

**Comment by ivyleavedtoadflax** [comment]
Btw there are also a number of files that seem to be artefacts of an OSX system - all these files prefixed with `_`

```
(virtualenv)  matthew@xps15  ~/.cache/wellcomeml/data  la conll 
.rw-r--r--  176 matthew  2 Jun  9:04 ._eng.testa
.rw-r--r-- 827k matthew  2 Jun  9:04 eng.testa
.rw-r--r-- 748k matthew  2 Jun  9:05 eng.testb
.rw-r--r-- 3.3M matthew  2 Jun  9:04 eng.train
(virtualenv)  matthew@xps15  ~/.cache/wellcomeml/data  la hoc  
.rwxr-xr-x  212 matthew  3 May  2019 ._dev.tsv
.rwxr-xr-x  212 matthew  1 Apr  2019 ._dev_docid.txt
.rwxr-xr-x  212 matthew  3 May  2019 ._original
.rwxr-xr-x  212 matthew  3 May  2019 ._test.tsv
.rwxr-xr-x  212 matthew  1 Apr  2019 ._test_docid.txt
.rwxr-xr-x  212 matthew  3 May  2019 ._train.tsv
.rwxr-xr-x  212 matthew  1 Apr  2019 ._train_docid.txt
.rwxr-xr-x 273k matthew  3 May  2019 dev.tsv
.rwxr-xr-x 1.6k matthew  1 Apr  2019 dev_docid.txt
drwxr-xr-x    - matthew  3 May  2019 original
.rwxr-xr-x 547k matthew  3 May  2019 test.tsv
.rwxr-xr-x 3.1k matthew  1 Apr  2019 test_docid.txt
.rwxr-xr-x 2.0M matthew  3 May  2019 train.tsv
.rwxr-xr-x  10k matthew  1 Apr  2019 train_docid.txt
(virtualenv)  matthew@xps15  ~/.cache/wellcomeml/data  la winer 
.rw-r--r--  176 matthew  1 Jun 10:25 ._CoarseNE.tar.bz2
.rw-r-----  176 matthew  1 Sep  2017 ._document.vocab
.rw-r--r--  176 matthew  1 Jun 10:30 ._Documents.tar.bz2
.rw-r--r--  176 matthew  1 Jun 10:32 ._README
.rw-r--r--  176 matthew 10 Jun 13:33 ._test.txt
.rw-r--r-- 6.1k matthew 10 Jun 12:52 .DS_Store
.rw-r--r-- 245M matthew  1 Jun 10:25 CoarseNE.tar.bz2
.rw-r-----  88M matthew  1 Sep  2017 document.vocab
.rw-r--r-- 1.9G matthew  1 Jun 10:30 Documents.tar.bz2
.rw-r--r-- 5.0k matthew  1 Jun 10:32 README
.rw-r--r-- 5.8M matthew 10 Jun 13:33 test.txt
.rw-r--r--  15M matthew 10 Jun 13:33 train.txt
```

If I open one (`conll/._eng.testa`), this is what i find:

```
Mac OS X        	2~°ATTR°  com.apple.lastuseddate#PSQ^Ö^	Èç
```

**Comment by aCampello** [comment]
Thanks! I think this was uploaded by @lizgzil or @nsorros (can you guys check?)

In the meantime, are you able to proceed with the issue ignoring those?

**Comment by ivyleavedtoadflax** [comment]
Yep that's no problem. What's more tricky is that the functions are very tightly coupled with the individual datasets, so it is hard to test them. `hoc` and `conll` are small, so probably the best way to test them is just to run them as part of test. `winer` is big though, so that one will take a bit of thought.

![image](https://user-images.githubusercontent.com/4583655/94953716-659cbc00-04be-11eb-8b35-1764e618dcfb.png)

**Comment by ivyleavedtoadflax** [comment]
That said conll and hoc are still megabyte scale, so its not ideal.

**Comment by aCampello** [comment]
I think adding a mock dataset to `/tests/data` is the preferred path. Perhaps we can add/upload mock datasets to S3 as well?

**Comment by ivyleavedtoadflax** [comment]
Yep that's what i was thinking, just building a mock dataset now

**Comment by lizgzil** [comment]
I may have missed something but test_winer and test_conll already use mock datasets kept in `tests/test_data`.

**Comment by lizgzil** [comment]
working on deleting those underscore files and updating s3 to not include them

**Comment by nsorros** [comment]
Fixed for hoc @ivyleavedtoadflax @lizgzil

**Comment by lizgzil** [comment]
@nsorros nice

**Comment by lizgzil** [comment]
should be corrected for winer and conll now too

**Comment by ivyleavedtoadflax** [comment]
> I may have missed something but test_winer and test_conll already use mock datasets kept in `tests/test_data`.

ooh sounds like I have been missing something!
