### ISSUE TITLE
New pip dependency resolver stalls builds

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/WellcomeML#195]
Build last lines
```
Collecting rsa<5,>=3.1.4
682  Downloading rsa-4.6-py3-none-any.whl (47 kB)
683
684  Downloading rsa-4.5-py2.py3-none-any.whl (36 kB)
685  Downloading rsa-4.4.1-py2.py3-none-any.whl (33 kB)
686  Downloading rsa-4.3-py2.py3-none-any.whl (36 kB)
687  Downloading rsa-4.2.tar.gz (46 kB)
688
689  Downloading rsa-4.1-py3-none-any.whl (32 kB)
690  Downloading rsa-4.0-py2.py3-none-any.whl (38 kB)
691  Downloading rsa-3.4.2-py2.py3-none-any.whl (46 kB)
692
693  Downloading rsa-3.4.1-py2.py3-none-any.whl (46 kB)
694
695  Downloading rsa-3.4-py2.py3-none-any.whl (46 kB)
696
697  Downloading rsa-3.3-py2.py3-none-any.whl (44 kB)
698
699  Downloading rsa-3.2.3-py2.py3-none-any.whl (44 kB)
700
701  Downloading rsa-3.2.2-py2.py3-none-any.whl (44 kB)
702
703  Downloading rsa-3.2-py2.py3-none-any.whl (43 kB)
704
705  Downloading rsa-3.1.4.tar.gz (36 kB)
706
707
708No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
709Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
710
711The build has been terminated
```

**Comment by nsorros** [comment]
Tried pinning all the version which did not fix the problem, possibly because the problem arises with a dependency, rsa in particular.

**Comment by nsorros** [comment]
Tried using the legacy resolver which threw another error about a C library
```
________________ ERROR collecting tests/test_bert_classifier.py ________________
722E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
723________________ ERROR collecting tests/test_bert_vectorizer.py ________________
724E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
725____________________ ERROR collecting tests/test_bilstm.py _____________________
726E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
727__________________ ERROR collecting tests/test_clustering.py ___________________
728E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
729______________________ ERROR collecting tests/test_cnn.py ______________________
730E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
731____________________ ERROR collecting tests/test_doc2vec.py ____________________
732E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
733________________ ERROR collecting tests/test_entity_linking.py _________________
734E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
735_____________ ERROR collecting tests/test_frequency_vectorizer.py ______________
736E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
737_______________ ERROR collecting tests/test_keras_vectorizer.py ________________
738E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
739___________________ ERROR collecting tests/test_ner_spacy.py ___________________
740E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
741___________________ ERROR collecting tests/test_sent2vec.py ____________________
742E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
743_______________ ERROR collecting tests/test_spacy_classifier.py ________________
744E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
745_____________ ERROR collecting tests/test_spacy_entity_linking.py ______________
746E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
747____________ ERROR collecting tests/test_transformers_tokenizer.py _____________
748E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
749__________________ ERROR collecting tests/test_vectorizer.py ___________________
750E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
751_______________ ERROR collecting tests/test_voting_classifier.py _______________
752E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
753________________ ERROR collecting tests/ml/test_keras_utils.py _________________
754E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
755_______ ERROR collecting tests/transformers/test_semantic_similarity.py ________
756E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

This is resolved by pinning numpy to 1.20.0 which btw creates a conflict with tensorflow that requires numpy to be less than 1.19.2

**Comment by nsorros** [comment]
So the next things I tried was to install the dependencies in master with the old pip with the goal of freezing the environment. This did not fix the above problem with the C header.

**Comment by nsorros** [comment]
The problem seems to originate in hdbscan library, there is actually an issue about it https://github.com/scikit-learn-contrib/hdbscan/issues/457

So i tried
```
pip uninstall hdbscan
pip install hdbscan --no-cache-dir --no-binary :all:
```

which threw
```
Collecting hdbscan
  Downloading hdbscan-0.8.26.tar.gz (4.7 MB)
     |████████████████████████████████| 4.7 MB 11.8 MB/s
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/nicksorros/code/WellcomeML/venv/bin/python3.7 /Users/nicksorros/code/WellcomeML/venv/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-build-env-v1em24bo/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy
       cwd: None
  Complete output (132 lines):
  Collecting setuptools
    Downloading setuptools-53.0.0.tar.gz (2.1 MB)
  Collecting wheel
    Downloading wheel-0.36.2.tar.gz (65 kB)
  Collecting cython
    Downloading Cython-0.29.21.tar.gz (2.1 MB)
  Collecting numpy
    Downloading numpy-1.20.0.zip (8.0 MB)
    Installing build dependencies: started
    Installing build dependencies: still running...
    Installing build dependencies: still running...
    Installing build dependencies: still running...
    Installing build dependencies: still running...
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: still running...
      Preparing wheel metadata: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /Users/nicksorros/code/WellcomeML/venv/bin/python3.7 /Users/nicksorros/code/WellcomeML/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/tmp4i4p7fs3
           cwd: /private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy
      Complete output (105 lines):
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_philox.pyx
      Processing numpy/random/_bounded_integers.pyx.in
      Processing numpy/random/_sfc64.pyx
      Processing numpy/random/_mt19937.pyx
      Processing numpy/random/bit_generator.pyx
      Processing numpy/random/mtrand.pyx
      Processing numpy/random/_generator.pyx
      Processing numpy/random/_pcg64.pyx
      Processing numpy/random/_common.pyx
      Cythonizing sources
      blas_opt_info:
      blas_mkl_info:
      customize UnixCCompiler
        libraries mkl_rt not found in ['/Users/nicksorros/code/WellcomeML/venv/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
        NOT AVAILABLE

      blis_info:
        libraries blis not found in ['/Users/nicksorros/code/WellcomeML/venv/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
        NOT AVAILABLE

      openblas_info:
        libraries openblas not found in ['/Users/nicksorros/code/WellcomeML/venv/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
        NOT AVAILABLE

      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries tatlas not found in ['/Users/nicksorros/code/WellcomeML/venv/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
        NOT AVAILABLE

      atlas_3_10_blas_info:
        libraries satlas not found in ['/Users/nicksorros/code/WellcomeML/venv/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
        NOT AVAILABLE

      atlas_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries ptf77blas,ptcblas,atlas not found in ['/Users/nicksorros/code/WellcomeML/venv/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
        NOT AVAILABLE

      atlas_blas_info:
      Running from numpy source directory.
      setup.py:485: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
        run_build = parse_setuppy_commands()
      Traceback (most recent call last):
        File "/Users/nicksorros/code/WellcomeML/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
          main()
        File "/Users/nicksorros/code/WellcomeML/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/nicksorros/code/WellcomeML/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-build-env-_157qs23/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-build-env-_157qs23/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 249, in run_setup
          self).run_setup(setup_script=setup_script)
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-build-env-_157qs23/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 513, in <module>
          setup_package()
        File "setup.py", line 505, in setup_package
          setup(**metadata)
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy/numpy/distutils/core.py", line 135, in setup
          config = configuration()
        File "setup.py", line 173, in configuration
          config.add_subpackage('numpy')
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy/numpy/distutils/misc_util.py", line 1021, in add_subpackage
          caller_level = 2)
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy/numpy/distutils/misc_util.py", line 990, in get_subpackage
          caller_level = caller_level + 1)
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy/numpy/distutils/misc_util.py", line 927, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "numpy/setup.py", line 8, in configuration
          config.add_subpackage('core')
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy/numpy/distutils/misc_util.py", line 1021, in add_subpackage
          caller_level = 2)
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy/numpy/distutils/misc_util.py", line 990, in get_subpackage
          caller_level = caller_level + 1)
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy/numpy/distutils/misc_util.py", line 927, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "numpy/core/setup.py", line 757, in configuration
          blas_info = get_info('blas_opt', 0)
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy/numpy/distutils/system_info.py", line 584, in get_info
          return cl().get_info(notfound_action)
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy/numpy/distutils/system_info.py", line 844, in get_info
          self.calc_info()
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy/numpy/distutils/system_info.py", line 1989, in calc_info
          if self._calc_info(blas):
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy/numpy/distutils/system_info.py", line 1981, in _calc_info
          return getattr(self, '_calc_info_{}'.format(name))()
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy/numpy/distutils/system_info.py", line 1945, in _calc_info_atlas
          info = get_info('atlas_blas')
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy/numpy/distutils/system_info.py", line 584, in get_info
          return cl().get_info(notfound_action)
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy/numpy/distutils/system_info.py", line 844, in get_info
          self.calc_info()
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy/numpy/distutils/system_info.py", line 1439, in calc_info
          atlas = self.check_libs2(lib_dirs, atlas_libs, [])
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy/numpy/distutils/system_info.py", line 1001, in check_libs2
          info = self._check_libs(lib_dirs, libs, opt_libs, exts)
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy/numpy/distutils/system_info.py", line 1057, in _check_libs
          found_dirs, found_libs = self._find_libs(lib_dirs, libs, exts)
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy/numpy/distutils/system_info.py", line 1041, in _find_libs
          found_lib = self._find_lib(lib_dir, lib, exts)
        File "/private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-install-wo2hzlgb/numpy/numpy/distutils/system_info.py", line 1022, in _find_lib
          raise RuntimeError(_accel_msg.format(filename=p[0]))
      RuntimeError: Found /usr/lib/libcblas.dylib, but that file is a symbolic link to the MacOS Accelerate framework, which is not supported by NumPy. You must configure the build to use a different optimized library, or disable the use of optimized BLAS and LAPACK by setting the environment variables NPY_BLAS_ORDER="" and NPY_LAPACK_ORDER="" before building NumPy.
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /Users/nicksorros/code/WellcomeML/venv/bin/python3.7 /Users/nicksorros/code/WellcomeML/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/tmp4i4p7fs3 Check the logs for full command output.
  WARNING: You are using pip version 20.1.1; however, version 21.0.1 is available.
  You should consider upgrading via the '/Users/nicksorros/code/WellcomeML/venv/bin/python3.7 -m pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/nicksorros/code/WellcomeML/venv/bin/python3.7 /Users/nicksorros/code/WellcomeML/venv/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/gt/x03b02gs5w3ch207t35d9ghr0000gn/T/pip-build-env-v1em24bo/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.
```

**Comment by nsorros** [comment]
Following the advice on the above error i did
```
export NPY_BLAS_ORDER=""
export NPY_LAPACK_ORDER=""
```

before rerunning `pip install hdbscan --no-cache-dir --no-binary :all:`

Installations succeeds this time, but the error persists.

**Comment by nsorros** [comment]
Not including hdbscan in WellcomeML resolves the C library problems

**Comment by nsorros** [comment]
Closing this as I created two separate issues #198 #197
